language: ruby
rvm:
  - 1.9.3

#Prevents installation of plugin's gemfile
gemfile: non-existent-gemfile

before_install:
  # Git repo of the Redmine
  - export MAIN_REPO="git@github.com:redmine/redmine.git"
  # Name of your plugin's repo
  - export REPO_NAME=due_date_reminder
  # Plugin's name/directory
  - export PLUGIN_NAME=$REPO_NAME
  - export TARGET_DIR="$HOME/redmine"
before_script: "./test/ci/before_script.sh"
script: "./test/ci/script.sh"

env:
  - "DB=mysql2 BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite"
  - "DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite"
